exclude: "^.run|^.idea"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
        files: \.py$
      - id: requirements-txt-fixer
      - id: name-tests-test
      - id: check-docstring-first
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        args: [ --config=.flake8 ]
        files: \.py$
        additional_dependencies: [
          flake8-return,
          flake8-printf-formatting,
          pep8-naming
        ]
  - repo:  https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit